Repository iwishiwasaneagle/boxofhope, pull requests merged in 2021-03, with the labels that each got.

#59 Api notifications w/ persistent storage + bug fix
  api/controllers/notificationsController.js
  api/package-lock.json
  api/package.json
  api/routes/apiRoutes.js
  api/server.js
Labels: bug, enhancement

#60 Io server
  .github/workflows/servers_ci.yml
  Doxyfile
  io_server/CMakeLists.txt
  io_server/apps/app.cpp
  io_server/include/io_server/io_home.h
  io_server/include/io_server/io_lcd.h
  io_server/include/io_server/io_nfc.h
  io_server/include/io_server/io_server.h
  io_server/include/io_server/lib.hpp
  io_server/include/utils/api.h
  io_server/src/CMakeLists.txt
  io_server/src/io_door.cpp
  io_server/src/io_home.cpp
  io_server/src/io_lcd.cpp
  io_server/src/io_nfc.cpp
  io_server/src/io_server.cpp
  io_server/src/lib.cpp
  io_server/src/utils/CMakeLists.txt
  io_server/src/utils/api.cpp
  io_server/test/CMakeLists.txt
  io_server/test/io_home.cpp
  io_server/test/io_server_utest.cpp
Labels: bug, documentation, enhancement

#61 Api dev
  api/README.md
  api/controllers/maskController.js
  api/controllers/notificationsController.js
  api/controllers/settingsController.js
  api/controllers/stateController.js
  api/models/maskModel.js
  api/models/notificationModel.js
  api/models/settingsModel.js
  api/models/stateModel.js
  api/package-lock.json
  api/package.json
  api/routes/apiRoutes.js
  api/server.js
  servers/boxofhopeConfig.h
Labels: documentation, enhancement

#74 Notification auto-send workflow
  .gitignore
  api/controllers/notificationsController.js
  api/controllers/userHomeController.js
  api/models/stateModel.js
  api/runners/notificationRunnable.js
  api/runners/userHomeRunnable.js
Labels: enhancement

#75 IO_Server 0.9
  .github/workflows/servers_ci.yml
  .gitignore
  io_server/.clang-format
  io_server/CMakeLists.txt
  io_server/apps/app.cpp
  io_server/include/io_server/io_door.h
  io_server/include/io_server/io_generic_runnable.h
  io_server/include/io_server/io_home.h
  io_server/include/io_server/io_lcd.h
  io_server/include/io_server/io_nfc.h
  io_server/include/io_server/io_server.h
  io_server/include/io_server/io_uvc.h
  io_server/include/utils/api.h
  io_server/src/CMakeLists.txt
  io_server/src/io_door.cpp
  io_server/src/io_home.cpp
  io_server/src/io_lcd.cpp
  io_server/src/io_nfc.cpp
  io_server/src/io_server.cpp
  io_server/src/io_uvc.cpp
  io_server/src/utils/api.cpp
  webapp/package-lock.json
Labels: enhancement

#78 Issue 77 - typo in initial notification model spec
  api/BoxOfHopeAPI.postman_collection.json
  api/models/notificationModel.js
Labels: bug

#79 Minor updates to how api url and ports are handled
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/src/components/masksList/MasksCard.js
  webapp/src/util/api.js
Labels: bug

#81 v1.0
  .github/workflows/api_ci.yml
  .github/workflows/servers_ci.yml
  .gitignore
  README.md
  api/BoxOfHopeAPI.postman_collection.json
  api/InitialTestEnvironment.postman_environment.json
  api/README.md
  api/controllers/maskController.js
  api/controllers/notificationsController.js
  api/controllers/settingsController.js
  api/controllers/stateController.js
  api/controllers/userHomeController.js
  api/models/notificationModel.js
  api/models/settingsModel.js
  api/models/stateModel.js
  api/models/userHomeModel.js
  api/package-lock.json
  api/package.json
  api/routes/apiRoutes.js
  api/runners/notificationRunnable.js
  api/runners/userHomeRunnable.js
  api/server.js
  io_server/.clang-format
  io_server/CMakeLists.txt
  io_server/README.md
  io_server/apps/app.cpp
  io_server/include/io_server/io_door.h
  io_server/include/io_server/io_generic_runnable.h
  io_server/include/io_server/io_home.h
  io_server/include/io_server/io_lcd.h
  io_server/include/io_server/io_nfc.h
  io_server/include/io_server/io_server.h
  io_server/include/io_server/io_uvc.h
  io_server/include/utils/api.h
  io_server/src/CMakeLists.txt
  io_server/src/io_door.cpp
  io_server/src/io_home.cpp
  io_server/src/io_lcd.cpp
  io_server/src/io_nfc.cpp
  io_server/src/io_server.cpp
  io_server/src/io_uvc.cpp
  io_server/src/utils/api.cpp
  io_server/test/io_home.cpp
  webapp/README.md
  webapp/package-lock.json
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/src/components/masksList/MasksCard.js
  webapp/src/util/api.js
Labels: bug, documentation, enhancement

#83 io_server v1.1
  io_server/CMakeLists.txt
  io_server/include/io_server/io_nfc.h
  io_server/include/utils/api.h
  io_server/src/io_door.cpp
  io_server/src/io_server.cpp
  io_server/src/io_uvc.cpp
  io_server/src/utils/api.cpp
Labels: bug, enhancement

#91 v1.1
  .github/workflows/servers_ci.yml
  README.md
  api/package.json
  api/runners/notificationRunnable.js
  io_server/.codecov.yml
  io_server/CMakeLists.txt
  io_server/include/io_server/io_nfc.h
  io_server/include/utils/api.h
  io_server/src/io_door.cpp
  io_server/src/io_server.cpp
  io_server/src/io_uvc.cpp
  io_server/src/utils/api.cpp
  io_server/test/util_api.cpp
  webapp/package-lock.json
Labels: bug, documentation, enhancement

#92 More io_server testing and docs
  .gitmodules
  io_server/include/io_server/io_door.h
  io_server/include/io_server/io_generic_runnable.h
  io_server/include/io_server/io_home.h
  io_server/include/io_server/io_nfc.h
  io_server/include/io_server/io_server.h
  io_server/include/io_server/io_uvc.h
  io_server/src/io_server.cpp
  io_server/test/io_generic_runnable.cpp
  io_server/test/io_server.cpp
Labels: documentation, testing

#101 v1.2 🤩
  .gitmodules
  api/.dockerignore
  api/BoxOfHopeAPI.postman_collection.json
  api/Dockerfile
  api/controllers/maskController.js
  api/controllers/stateController.js
  api/controllers/userHomeController.js
  api/models/userHomeModel.js
  api/package-lock.json
  api/package.json
  api/routes/api-docs.js
  api/routes/apiRoutes.js
  docker-compose.yml
  io_server/.clang-format
  io_server/.codecov.yml
  io_server/ARCHITECTURE.md
  io_server/CMakeLists.txt
  io_server/README.md
  io_server/apps/app.cpp
  io_server/include/io_server/io_door.h
  io_server/include/io_server/io_generic_runnable.h
  io_server/include/io_server/io_home.h
  io_server/include/io_server/io_lcd.h
  io_server/include/io_server/io_nfc.h
  io_server/include/io_server/io_server.h
  io_server/include/io_server/io_uvc.h
  io_server/include/utils/api.h
  io_server/src/io_door.cpp
  io_server/src/io_home.cpp
  io_server/src/io_nfc.cpp
  io_server/src/io_server.cpp
  io_server/src/io_uvc.cpp
  io_server/src/utils/api.cpp
  io_server/test/io_generic_runnable.cpp
  io_server/test/io_home.cpp
  io_server/test/io_server.cpp
  io_server/test/util_api.cpp
  webapp/.dockerignore
  webapp/.env.development
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/components/bottomBar/BottomBar.js
  webapp/src/components/masksList/MasksCard.js
  webapp/src/components/statsCard/StatsCard.js
  webapp/src/components/statsCard/StatsChart.js
  webapp/src/components/statsCard/statsCard.css
  webapp/src/index.css
  webapp/src/util/api.js
Labels: bug, documentation, enhancement, testing
